language: csharp
mono: none
dotnet: 2.1.302
services:
  - postgresql
before_script:
  - dotnet restore
  - psql -c "CREATE DATABASE RGRDatabase;" -U postgres
script:  
  - cd RGRProject
  - dotnet ef database update
  - cd ..
  - dotnet test ./XUnitTests