// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RGRProject.Models;

namespace RGRProject.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20181226122257_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RGRProject.Models.Booking", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("BookingFinish");

                    b.Property<DateTime?>("BookingStart");

                    b.Property<string>("CustomerContact");

                    b.Property<string>("CustomerName");

                    b.Property<int>("PlaceID");

                    b.Property<int?>("Rating");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.ToTable("Bookings");

                    b.HasData(
                        new { ID = 1, BookingFinish = new DateTime(2018, 12, 25, 17, 30, 0, 0, DateTimeKind.Unspecified), BookingStart = new DateTime(2018, 12, 25, 16, 30, 0, 0, DateTimeKind.Unspecified), CustomerContact = "0503234343", CustomerName = "Іванов Іван", PlaceID = 1, Rating = 4, Status = 2 },
                        new { ID = 2, BookingFinish = new DateTime(2018, 12, 26, 18, 0, 0, 0, DateTimeKind.Unspecified), BookingStart = new DateTime(2018, 12, 26, 16, 30, 0, 0, DateTimeKind.Unspecified), CustomerContact = "0503234345", CustomerName = "Іванов Іван", PlaceID = 2, Rating = 5, Status = 2 },
                        new { ID = 3, BookingStart = new DateTime(2018, 12, 27, 16, 30, 0, 0, DateTimeKind.Unspecified), CustomerContact = "0503234341", CustomerName = "Петров Петро", PlaceID = 1, Status = 1 }
                    );
                });

            modelBuilder.Entity("RGRProject.Models.Place", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Description");

                    b.Property<string[]>("Facilities");

                    b.Property<string[]>("Images");

                    b.Property<double>("Lattitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<int>("Rating");

                    b.Property<string>("Site");

                    b.Property<int>("Status");

                    b.HasKey("ID");

                    b.ToTable("Places");

                    b.HasData(
                        new { ID = 1, Address = "проспект Перемоги, 45, Київ, 03057", Description = "Поздний ужин, хорошая коктейльная карта", Facilities = new[] { "Wifi", "Доставка" }, Images = new[] { "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiCjJHour3fAhUwz4UKHaSGBTgQjRx6BAgBEAU&url=https%3A%2F%2Fmistercat.com.ua%2F&psig=AOvVaw3LwcdGYqDLFeqkFC_275Bn&ust=1545912455470417" }, Lattitude = 50.4316, Longitude = 30.516, Name = "Mister Cat", Phone = "044 578 1690", Rating = 4, Site = "https://mistercat.com.ua/", Status = 1 },
                        new { ID = 2, Address = "проспект Перемоги, 45, Київ, 03057", Description = "Поздний ужин, хорошая коктейльная карта", Facilities = new[] { "Wifi", "Доставка" }, Images = new[] { "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiCjJHour3fAhUwz4UKHaSGBTgQjRx6BAgBEAU&url=https%3A%2F%2Fmistercat.com.ua%2F&psig=AOvVaw3LwcdGYqDLFeqkFC_275Bn&ust=1545912455470417" }, Lattitude = 50.432, Longitude = 30.5155, Name = "Mister Cat", Phone = "044 578 1690", Rating = 4, Site = "https://mistercat.com.ua/", Status = 1 },
                        new { ID = 3, Address = "проспект Перемоги, 45, Київ, 03057", Description = "Поздний ужин, хорошая коктейльная карта", Facilities = new[] { "Wifi", "Доставка" }, Images = new[] { "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiCjJHour3fAhUwz4UKHaSGBTgQjRx6BAgBEAU&url=https%3A%2F%2Fmistercat.com.ua%2F&psig=AOvVaw3LwcdGYqDLFeqkFC_275Bn&ust=1545912455470417" }, Lattitude = 50.431282, Longitude = 30.51632, Name = "Mister Cat", Phone = "044 578 1690", Rating = 4, Site = "https://mistercat.com.ua/", Status = 1 },
                        new { ID = 4, Address = "проспект Перемоги, 45, Київ, 03057", Description = "Поздний ужин, хорошая коктейльная карта", Facilities = new[] { "Wifi", "Доставка" }, Images = new[] { "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiCjJHour3fAhUwz4UKHaSGBTgQjRx6BAgBEAU&url=https%3A%2F%2Fmistercat.com.ua%2F&psig=AOvVaw3LwcdGYqDLFeqkFC_275Bn&ust=1545912455470417" }, Lattitude = 50.43134, Longitude = 30.51623, Name = "Mister Cat", Phone = "044 578 1690", Rating = 4, Site = "https://mistercat.com.ua/", Status = 1 },
                        new { ID = 5, Address = "проспект Перемоги, 45, Київ, 03057", Description = "Поздний ужин, хорошая коктейльная карта", Facilities = new[] { "Wifi", "Доставка" }, Images = new[] { "https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiCjJHour3fAhUwz4UKHaSGBTgQjRx6BAgBEAU&url=https%3A%2F%2Fmistercat.com.ua%2F&psig=AOvVaw3LwcdGYqDLFeqkFC_275Bn&ust=1545912455470417" }, Lattitude = 50.431, Longitude = 30.51612, Name = "Mister Cat", Phone = "044 578 1690", Rating = 4, Site = "https://mistercat.com.ua/", Status = 1 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
